# Generated by Django 6.1.1 on 2026-09-29 20:40

from django.db import migrations


def authorize_books(apps, schema_editor): # "author-ize" get it X-D
    Author = apps.get_model("catalog", "Author")
    Book = apps.get_model("catalog", "Book")
    BookAuthor = apps.get_model("catalog", "BookAuthor")

    for book in Book.objects.all():
        if book.author_id is not None:
            BookAuthor.objects.create(book=book, author_id=book.author_id, author_order=1)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookauthor_book_authors'),
    ]

    operations = [
        migrations.RunPython(authorize_books),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
    ]
